version: "3.5"

services:

  samba:
    container_name: samba
    image: dperson/samba
    command: '-p -r'
    ports:
      - "139:139"
      - "445:445"
    volumes:
      - /media:/media
    environment:
      USERID: "1000"
      GROUPID: "1000"
      SHARE: "buffalo;/media/wdred-alpha/buffalo;yes;no;yes;all;none;;buffalo"
      SHARE1: "maxtor;/media/wdred-alpha/maxtor;yes;no;yes;all;none;;maxtor"
    restart: unless-stopped

  #nfs:
    #container_name: nfs
    #image: erichough/nfs-server
    #volumes:
      #- /media:/media
      #- /lib/modules:/lib/modules:ro
    #environment:
      #NFS_DISABLE_VERSION_3: "1"
      #NFS_EXPORT_0: "/media/wdred-alpha *(rw,async,insecure,no_subtree_check,all_squash,anonuid=1000,anongid=1000)"
      #NFS_EXPORT_1: "/media/wdred-bravo *(rw,async,insecure,no_subtree_check,all_squash,anonuid=1000,anongid=1000)"
      #NFS_EXPORT_2: "/media/wdred-charlie *(rw,async,insecure,no_subtree_check,all_squash,anonuid=1000,anongid=1000)"
    #cap_add:
      #- SYS_ADMIN
      #- SYS_MODULE
    #ports:
      #- "2049:2049"
    #security_opt:
      #- apparmor=erichough-nfs
    #restart: unless-stopped
