#!/bin/bash

cd ~

echo "Updating and Upgrading"
if [ "$USER" == "root" ]; then
  sudo apt update && sudo apt full-upgrade -y
else
  sudo apt update && sudo apt upgrade -y
fi

bash <(curl -s https://raw.githubusercontent.com/damonmorgan/home-server/master/scripts/user)
bash <(curl -s https://raw.githubusercontent.com/damonmorgan/home-server/master/scripts/ssh)
bash <(curl -s https://raw.githubusercontent.com/damonmorgan/home-server/master/scripts/docker)
bash <(curl -s https://raw.githubusercontent.com/damonmorgan/home-server/master/scripts/storage)
if [[ -z $(dpkg -l | grep 'wireguard-tools') ]]; then
  bash <(curl -s https://raw.githubusercontent.com/damonmorgan/home-server/master/scripts/wireguard)
fi
bash <(curl -s https://raw.githubusercontent.com/damonmorgan/home-server/master/scripts/entertainer)

echo "cleanup"
sudo apt autoremove
