#!/bin/bash

if [ "$USER" != "root" ]; then
  cd ~

  if [[ -z $(dpkg -l | grep 'jq') ]]; then
    echo "Ensure required tools installed"
    sudo apt-get update
    sudo apt-get -y install \
      apt-transport-https \
      ca-certificates \
      curl \
      gnupg-agent \
      software-properties-common \
      jq

    if [[ -z $(dpkg -l | grep 'haveged') ]]; then
      read -p 'Is the host a small instance cloud server? (Y/n) ' CLOUD_SERVER_HOST
      if [ "$CLOUD_SERVER_HOST" == "Y" ]; then
        sudo apt-get -y install \
          haveged
      fi
    fi
  fi

  if [[ -z $(docker --version | grep 'Docker version') ]]; then
    echo "Install Docker"
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

    sudo add-apt-repository \
     "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
     $(lsb_release -cs) \
     stable"

    sudo apt-get update
    sudo apt-get -y install docker-ce docker-ce-cli containerd.io

    sudo groupadd docker
    sudo usermod -aG docker $USER

    sudo systemctl enable docker

    LATEST_VERSION=$(curl --silent https://api.github.com/repos/docker/compose/releases/latest | jq .name -r)
    sudo curl -L "https://github.com/docker/compose/releases/download/${LATEST_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

    sudo chmod +x /usr/local/bin/docker-compose

    su $USER
  else
    cd ~
    LATEST_VERSION=$(curl --silent https://api.github.com/repos/docker/compose/releases/latest | jq .name -r)
    echo $(docker-compose --version)
    echo $LATEST_VERSION
    if [[ -z $(docker-compose --version | grep $LATEST_VERSION) ]]; then
      echo "upgrading docker-compose"

      sudo rm /usr/local/bin/docker-compose
      sudo curl -L "https://github.com/docker/compose/releases/download/${LATEST_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      sudo chmod +x /usr/local/bin/docker-compose
    fi
  fi
else
  echo "Logged in as root. Please login as a sudo user"
fi
