#!/bin/bash

if [ "$USER" != "root" ]; then
  cd ~

  if [[ -z $(dpkg -l | grep 'wireguard-tools') ]]; then
    echo "Ensure required tools installed"
    sudo apt-get -y install \
      wireguard-tools \
      mawk \
      grep \
      iproute2 \
      qrencode \
      wireguard
  fi

  cd /media/wdred-alpha/wireguard-config

  wget https://raw.githubusercontent.com/burghardt/easy-wg-quick/master/easy-wg-quick -O easy-wg-quick
  chmod +x easy-wg-quick

  if [[ ! -f "extnetip.txt" ]]; then
    read -p 'External IP or DynDNS address (leave blank to discover): ' WIREGUARD_IP
    if [ -n "$WIREGUARD_IP" ]; then
      echo $WIREGUARD_IP > extnetip.txt
    else
      curl ifconfig.co/ip > extnetip.txt
    fi
  fi

  if [[ ! -f "portno.txt" ]]; then
    read -p 'Wireguard Port (leave blank for random): ' WIREGUARD_PORT
    if [ -n "$WIREGUARD_PORT" ]; then
      echo $WIREGUARD_PORT > portno.txt
    fi
  fi

  read -p 'Use local dns for wireguard clients? (Y/n) ' USE_LOCAL_DNS
  rm intnetdns.txt
  rm intnet6dns.txt

  if [ "$USE_LOCAL_DNS" == "Y" ]; then
    ip addr sh $(ip route sh | awk '$1 == "default" { print $5 }') | grep 'inet ' | xargs | awk -F'[ /]' '{ print $2 }' > intnetdns.txt
    touch intnet6dns.txt
  fi

  read -p 'Wireguard Client Name: ' WG_CLIENT_NAME
  sudo systemctl stop wg-quick@wghub
  ./easy-wg-quick $WG_CLIENT_NAME
  sudo cp wghub.conf /etc/wireguard/wghub.conf
  sudo chown -v root:root /etc/wireguard/wghub.conf
  sudo chmod -v 600 /etc/wireguard/wghub.conf
  sudo systemctl enable wg-quick@wghub
  sudo systemctl daemon-reload
  sudo systemctl start wg-quick@wghub

  cd ~

  sudo wg show
fi
